import React from "react";
import Head from "next/head";
import OpenAILoginContent from "@/components/login/OpenAILoginContent";

const Login = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/openailogin.jpg" />
      </Head>
      <OpenAILoginContent />
    </>
  );
};

export default Login;
